#!/bin/bash
# Download the licenses mentioned in this ticket: https://fossa.zendesk.com/agent/tickets/996
# - Bouncy Castle License: https://bouncycastle.org/licence.html
# - Creative Commons Copyright-Only Dedication: https://creativecommons.org/licenses/publicdomain/
# - Cup Parser Generator: http://www2.cs.tum.edu/projects/cup/licence.php
# - DOM4J License: http://dom4j.sourceforge.net/dom4j-1.6.1/license.html
# - Eclipse Distribution License v1.0: http://www.eclipse.org/org/documents/edl-v10.php
# - Honest Public License: https://web.archive.org/web/20090301190743/http://www.opensourcestrategies.com/HPLv1.1.txt
# - MX4J License: http://mx4j.sourceforge.net/docs/ch01s06.html
# - Server Side Public License (SSPL): https://www.mongodb.com/licensing/server-side-public-license
# - ACE License: http://www.cs.wustl.edu/~schmidt/ACE-copying.html
# - DejaVu Fonts (Bitstream Vera/Arev licenses): http://dejavu-fonts.org/wiki/index.php?title=License
# - FSF autoconf license: http://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=tree
# - License for CERN packages in COLT: https://dst.lbl.gov/ACSSoftware/colt/license.html
# - Nuclide License: https://github.com/facebookarchive/nuclide/blob/master/LICENSE
# - Open Grid Forum License: https://www.ogf.org/ogf/doku.php/about/copyright
# - Service+Component+Architecture+Specifications: http://web.archive.org/web/20080704184203/http://www.osoa.org/xmlns/sca/1.0/license.txt
# - The Romantic WTF public license: https://github.com/pygy/gosub/blob/master/LICENSE
# - UK Open Government License: https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
# - W3C Community Contributor License Agreement: https://www.w3.org/community/about/agreements/cla/
